version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: news_aggregator
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8181:8181
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    # volumes:
    #   - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app

  db:
    image: mysql:8.0.21
    environment:
      MYSQL_DATABASE: "news_aggregator"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge
